### ISSUE TITLE
Keyboard Shortcuts doesn't respect Keyboard Distribution

### ISSUE THREAD

**Issue by ralgozino** [mattermost/desktop#721]
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**
The mattermost deksotp app doesn't respect Keyboard Distribution for keyboard shortcuts.

**Steps to reproduce**

- Operating System: Windows 10 Home Edition (Spanish)
- Mattermost Desktop App version: 4.0.0
- Mattermost Server version: Latest with GitLab Omnibus

Pressing `AltGr + backtick` keys with a latin-american spanish keyboard distributions opens Keyboard Shortcuts. Overlapping an US distribution over the Latinamerican this would be the equivalent of pressing `Alt + /`.

**Expected behavior**

The character ` should appear.

**Observed behavior**

Keyboard shortcuts help dialog appears and the ` character is ommited.

**Comment by jasonblais** [comment]
@ralgozino Does this reproduce for you on the browser?

We fixed an issue that sounds similar to this one. It'll be fixed in Mattermost v4.9, which will ship in GitLab 10.8: https://github.com/mattermost/mattermost-server/issues/7665

**Comment by jasonblais** [comment]
@ralgozino Closing the issue as it should be resolved in GitLab 10.8 that ships on May 22nd.

Once you've upgraded, let us know if the issue isn't resolved and we can reopen this.

**Comment by ralgozino** [comment]
@jasonblais  Sorry for the delay, this behavior also happens in Google Chrome but doesn't happen in Firefox. Both up to date versions. So seems to be the same as mattermost/mattermost-server#7665

I Will check with Mattermost v4.9 and let you know.
Thank you!

**Comment by jasonblais** [comment]
Thanks @ralgozino, sounds good! 👍

**Comment by ralgozino** [comment]
Hello @jasonblais ! We've updated to Mattermost server 4.10.1 and the backtick with Chrome works as expected but still doesn't work in the Desktop app v4.1.2 (same behaviour as before, I get the shortcuts pop-up instead of the backtick). So seems to be fixed server-side, but no client-side.

**Comment by jasonblais** [comment]
Thanks @ralgozino for the heads up! I created a ticket for it here https://mattermost.atlassian.net/browse/MM-11077

**Comment by ralgozino** [comment]
Hello @jasonblais ! Just to let you know that with Mattermost desktop client 4.1.2 and Mattermost Version: 5.1.1 the backticks work as expected 😃

**Comment by jasonblais** [comment]
Awesome! Glad to hear :)
